# Generated by Django 5.2.13 on 2026-04-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('banned', 'Banned'), ('warning', 'Warning')], default='active', max_length=20),
        ),
    ]
