# Generated by Django 6.0.4 on 2026-04-14 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Lý do từ chối / ẩn / khóa / xóa', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, help_text='Thời điểm Admin xử lý', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Admin đã xử lý bài viết này', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('HIDDEN', 'Hidden'), ('LOCKED', 'Locked')], default='PENDING', max_length=20),
        ),
    ]
