# Generated by Django 6.0.3 on 2026-04-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_post_rejection_reason_post_reviewed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.JSONField(blank=True, default=list, help_text='List of image URLs'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_anonymous',
            field=models.BooleanField(default=False, help_text='Post anonymously'),
        ),
    ]
