# Generated by Django 6.0.3 on 2026-04-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_post_images_post_is_anonymous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='images',
            field=models.JSONField(blank=True, default=list, help_text='Danh sách URL của các tệp minh chứng (ảnh/video)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_anonymous',
            field=models.BooleanField(default=False, help_text='Nếu true, thông tin tác giả sẽ bị ẩn trên giao diện public'),
        ),
    ]
