# Generated by Django 6.0.3 on 2026-04-17 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_blacklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentreport',
            name='target_type',
            field=models.CharField(choices=[('POST', 'Post'), ('COMMENT', 'Comment'), ('USER', 'User')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='target_type',
            field=models.CharField(choices=[('POST', 'Post'), ('COMMENT', 'Comment'), ('USER', 'User')], max_length=20),
        ),
        migrations.AlterField(
            model_name='targetmedia',
            name='target_type',
            field=models.CharField(choices=[('POST', 'Post'), ('COMMENT', 'Comment'), ('USER', 'User')], max_length=20),
        ),
    ]
