# Generated by Django 6.0.4 on 2026-04-18 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_post_images_alter_reaction_reaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_anonymous',
            field=models.BooleanField(default=False, help_text='True khi tác giả bình luận vào chính bài viết ẩn danh của mình. Server tự set — FE không gửi trường này.'),
        ),
    ]
