# Generated by Django 6.0.4 on 2026-05-01 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_status'),
        ('api', '0009_comment_is_anonymous'),
    ]

    operations = [
    ]
