# Generated by Codex on 2026-05-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_merge_20260501_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ai_analysis_status',
            field=models.CharField(
                choices=[
                    ('NOT_ANALYZED', 'Not analyzed'),
                    ('PROCESSING', 'Processing'),
                    ('COMPLETED', 'Completed'),
                    ('FAILED', 'Failed'),
                ],
                default='NOT_ANALYZED',
                help_text='Trang thai phan tich noi dung bang AI',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='post',
            name='ai_analysis_result',
            field=models.JSONField(
                blank=True,
                help_text='Ket qua goi y AI dang JSON cho Admin',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='post',
            name='ai_analysis_provider',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Nguon phan tich: openai, gemini, local',
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name='post',
            name='ai_analysis_error',
            field=models.TextField(
                blank=True,
                default='',
                help_text='Loi khi goi API AI, neu co',
            ),
        ),
        migrations.AddField(
            model_name='post',
            name='ai_analyzed_at',
            field=models.DateTimeField(
                blank=True,
                help_text='Thoi diem phan tich AI gan nhat',
                null=True,
            ),
        ),
    ]
